config/routes.rb
Rails.application.routes.draw do
  resources :flights, only: :index
  root 'flights#index'
  resources :bookings, only: [:show, :new, :create]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: :Flight, foreign_key: :from_airport_id  
    has_many :arriving_flights, class_name: :Flight, foreign_key: :to_airport_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :from_airport, class_name: :Airport
    belongs_to :to_airport, class_name: :Airport
    has_many :bookings

    def self.dates 
        all.map{|d| d.start.strftime("%d/%m/%Y")}.uniq
    end

    def self.search(params)
        flights = where("from_airport_id = ? AND to_airport_id = ?", params[:from_airport], params[:to_airport])
        ids = []
        flights.find_each do |f|
            ids << f.id if f.start.strftime("%d/%m/%Y") == params[:date]
        end
        find(ids)
    end

    def hour
        start.strftime("%H:%M")
    end

    def date
        start.strftime("%d/%m/%Y")
    end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end
  
  def new
    @flight = Flight.find(params[:flight][:id])
    @booking = Booking.new 
    n_passengers = params[:passengers].to_i
    n_passengers.times{ @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      PassengerMailer.with(booking: @booking).booking_email.deliver_now
      redirect_to @booking
    else
      render :new
    end
    
  end

  private
    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email]) 
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    
    @selected_flights = Flight.search(flight_params)
    @info = @selected_flights.first
  end

private

    def flight_params
      params.permit(:to_airport, :from_airport, :passegers, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Booking</h1>
<ul>
    <li><%= "Flight id: #{@flight.id}" %></li>
    <li><%= "Date: #{@flight.date} at #{@flight.hour}" %></li>
    <li><%= "Departure: #{@flight.from_airport.code}" %></li>
    <li><%= "Destination: #{@flight.to_airport.code}" %></li>
</ul>

<%= form_with model: Booking.new, url: bookings_path, local: true do |f|%>
    <%= f.hidden_field :flight_id, value: @flight.id %>
    Passengers:
    <ul>
    <%= f.fields_for :passengers, @booking.passengers do |p|%>
        <li>
            <%= p.label :name, 'Name: '%>
            <%= p.text_field :name %><br>
            <%= p.label :email, 'Email: '%>
            <%= p.email_field :email %>
        </li>
    <%end%>
    </ul>
    <%= f.submit 'Book it!' %>
<% end %>

app/views/bookings/show.html.erb
<h1><%= "Booking #{@booking.id}"%></h1>
<ul>
    <li><%= "Flight id: #{@booking.flight.id}" %></li>
    <li><%= "Date: #{@booking.flight.date} at #{@booking.flight.hour}" %></li>
    <li><%= "Departure: #{@booking.flight.from_airport.code}" %></li>
    <li><%= "Destination: #{@booking.flight.to_airport.code}" %></li>
    <li>Passengers:</li>
    <ul>
    <% @booking.passengers.find_each do |p|%>
        <li><%= p.name%></li>
    <%end%>
    </ul>
</ul>

app/views/flights/_flight_hour_form.html.erb
<h3>
    <%= "Flights from #{@info.from_airport.code} 
    to #{@info.to_airport.code} on #{@info.date}"%> 
</h3>

<%=form_with url: new_booking_path, method: :get, local: true do%>
    <%= hidden_field_tag :passengers, params[:passengers] %>
    <%= collection_radio_buttons :flight, :id, @selected_flights, :id, :hour %><br>
    <%= submit_tag 'Book it!'%>
<%end%>

app/views/flights/index.html.erb
<h1>Flights</h1>



<%= form_with url: root_path, method: :get, local: true do %>

    <%= label_tag :departure, 'Departure:' %>
    <%= select_tag :from_airport, options_from_collection_for_select(Airport.all, :id, :code)%>
    <%= label_tag :arrival, 'Arrival:' %>
    <%= select_tag :to_airport, options_from_collection_for_select(Airport.all, :id, :code)%>
    <%= label_tag :passengers, 'Number of Passengers:'%>
    <%= select_tag :passengers, options_for_select([['1', 1], ['2', 2], ['3', 3], ['4', 4]])%>
    <%= label_tag :date, 'Date:'%>
    <%= select_tag :date, options_for_select(Flight.dates) %>

    <%= submit_tag 'Search'%>
<%end%>

<%unless @selected_flights.nil? || @selected_flights.empty?%>
    <%= render 'flight_hour_form'%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>